// Config loader: reads TOML, applies env overrides, returns a Config.
//
// Layering (highest priority last):
//   1. ~/.pun/config.toml  (or $PUN_CONFIG)
//   2. env vars: PUN_WORKSPACE, PUN_AUDIT_LOG, PUN_DEFAULT_PROFILE
//   3. CLI flags passed to loadConfig()

const std = @import("std");
const util = @import("../util.zig");
const toml = @import("parser.zig");
const schema = @import("schema.zig");
const Config = schema.Config;

pub const DEFAULT_CONFIG_PATH = "~/.pun/config.toml";

pub fn loadConfig(
    alloc: std.mem.Allocator,
    cfg_path: ?[]const u8,
    workspace_override: ?[]const u8,
    profile_override: ?[]const u8,
) !Config {
    const path_expanded = if (cfg_path) |p|
        try util.expandPath(alloc, p)
    else if (std.process.getEnvVarOwned(alloc, "PUN_CONFIG") catch null) |p| p
    else
        try util.expandPath(alloc, DEFAULT_CONFIG_PATH);
    defer alloc.free(path_expanded);

    var cfg: Config = undefined;
    if (std.fs.cwd().openFile(path_expanded, .{})) |f| {
        defer f.close();
        const stat = try f.stat();
        const buf = try alloc.alloc(u8, stat.size);
        defer alloc.free(buf);
        _ = try f.readAll(buf);

        const root = toml.parse(alloc, buf) catch |e| {
            std.debug.print("pun: failed to parse {s}: {}\n", .{ path_expanded, e });
            // Fall back to defaults
            cfg = try schema.defaultConfig(alloc);
            try applyEnvOverrides(alloc, &cfg, workspace_override, profile_override);
            return cfg;
        };
        defer toml.freeTable(alloc, root);
        cfg = try schema.fromToml(alloc, root);
    } else |_| {
        // No config file — use defaults
        cfg = try schema.defaultConfig(alloc);
    }

    try applyEnvOverrides(alloc, &cfg, workspace_override, profile_override);
    return cfg;
}

fn applyEnvOverrides(
    alloc: std.mem.Allocator,
    cfg: *Config,
    workspace_override: ?[]const u8,
    profile_override: ?[]const u8,
) !void {
    // PUN_WORKSPACE
    if (workspace_override) |ws| {
        alloc.free(cfg.security.workspace);
        cfg.security.workspace = try util.expandPath(alloc, ws);
        alloc.free(cfg.shell.workspace);
        cfg.shell.workspace = try util.expandPath(alloc, ws);
    } else if (std.process.getEnvVarOwned(alloc, "PUN_WORKSPACE") catch null) |ws| {
        defer alloc.free(ws);
        alloc.free(cfg.security.workspace);
        cfg.security.workspace = try util.expandPath(alloc, ws);
        alloc.free(cfg.shell.workspace);
        cfg.shell.workspace = try util.expandPath(alloc, ws);
    }
    // PUN_AUDIT_LOG
    if (std.process.getEnvVarOwned(alloc, "PUN_AUDIT_LOG") catch null) |s| {
        defer alloc.free(s);
        alloc.free(cfg.security.audit_log);
        cfg.security.audit_log = try util.expandPath(alloc, s);
    }
    // PUN_DEFAULT_PROFILE
    var prof: ?[]const u8 = profile_override;
    if (prof == null) {
        prof = std.process.getEnvVarOwned(alloc, "PUN_DEFAULT_PROFILE") catch null;
    }
    if (prof) |p| {
        if (cfg.profiles.contains(p)) {
            alloc.free(cfg.active_profile);
            cfg.active_profile = try alloc.dupe(u8, p);
        }
    }
}

/// Write a starter config.toml to ~/.pun/config.toml.
/// Does NOT overwrite if the file already exists.
pub fn initConfig(alloc: std.mem.Allocator) !void {
    const path = try util.expandPath(alloc, DEFAULT_CONFIG_PATH);
    defer alloc.free(path);

    // Check existence
    if (std.fs.cwd().openFile(path, .{})) |f| {
        f.close();
        try stdoutPrint("Config already exists at {s}\n", .{path});
        return;
    } else |_| {}

    const dir = std.fs.path.dirname(path) orelse ".";
    try std.fs.cwd().makePath(dir);

    const template =
        \\# pun configuration — see https://pun.dev/config for full docs.
        \\# Generated by `pun config init`.
        \\
        \\[providers.anthropic]
        \\kind = "anthropic"
        \\api_key_env = "ANTHROPIC_API_KEY"
        \\default_model = "claude-sonnet-4-5"
        \\
        \\[providers.openai]
        \\kind = "openai"
        \\api_key_env = "OPENAI_API_KEY"
        \\default_model = "gpt-4.1"
        \\
        \\# Example: any OpenAI-compatible endpoint (Groq, Together, Ollama, vLLM, etc.)
        \\# [providers.ollama]
        \\# kind = "openai_compat"
        \\# base_url = "http://localhost:11434/v1"
        \\# api_key_env = "OLLAMA_KEY"
        \\# default_model = "llama3.1:70b"
        \\
        \\[shell]
        \\workspace = "~/projects"
        \\allowlist = ["ls", "cat", "grep", "rg", "git", "python", "pytest", "ruff", "make", "zig", "cargo"]
        \\denylist_regex = [
        \\  "rm\\s+-rf\\s+/",
        \\  ":\\(\\)\\s*\\{\\s*:\\|:&\\s*\\}",
        \\  "\\bmkfs\\b",
        \\  "\\bdd\\s+if=",
        \\  "\\bchmod\\s+-R\\s+777\\s+/",
        \\  ">\\s*/dev/sd",
        \\  "\\bsudo\\s+rm\\b",
        \\]
        \\timeout_seconds = 30
        \\allow_network = false
        \\allow_sudo = false
        \\env_passthrough = ["PATH", "HOME", "LANG", "LC_ALL", "TERM"]
        \\# docker_image = "ubuntu:22.04"   # uncomment to run all shell commands inside Docker
        \\
        \\[security]
        \\workspace = "~/projects"
        \\audit_log = "~/.pun/audit.jsonl"
        \\vault_path = "~/.pun/vault.age"
        \\vault_passphrase_env = "PUN_VAULT_PASSPHRASE"
        \\prompt_injection_guard = true
        \\require_confirmation_for_writes_outside_workspace = true
        \\require_confirmation_for_shell_not_in_allowlist = true
        \\
        \\[security.token_budget]
        \\per_session = 500000
        \\per_step = 50000
        \\warn_at_percent = 80
        \\
        \\[security.network]
        \\allowlist = [
        \\  "api.anthropic.com",
        \\  "api.openai.com",
        \\  "generativelanguage.googleapis.com",
        \\  "api.deepseek.com",
        \\  "api.mistral.ai",
        \\  "api.x.ai",
        \\  "open.bigmodel.cn",
        \\]
        \\default_allow = false
        \\
        \\[profiles.default]
        \\provider = "anthropic"
        \\model = "claude-sonnet-4-5"
        \\temperature = 0.3
        \\max_tokens = 8192
        \\
        \\[profiles.quick]
        \\provider = "anthropic"
        \\model = "claude-haiku-4"
        \\temperature = 0.2
        \\max_tokens = 4096
        \\
        \\[profiles.deep]
        \\provider = "anthropic"
        \\model = "claude-opus-4-1"
        \\temperature = 0.4
        \\max_tokens = 16384
        \\
        \\default_profile = "default"
        \\
    ;

    var f = try std.fs.cwd().createFile(path, .{});
    defer f.close();
    try f.writeAll(template);

    // Create workspace
    const ws = try util.expandPath(alloc, "~/projects");
    defer alloc.free(ws);
    std.fs.cwd().makePath(ws) catch {};

    try stdoutPrint("Wrote {s}\nCreated workspace at {s}\n", .{ path, ws });
    try stdoutPrint(
        \\Next steps:
        \\  1) Set your API keys in env vars (e.g. export ANTHROPIC_API_KEY=sk-...)
        \\     OR store them in the vault: pun vault set anthropic sk-ant-...
        \\  2) Run `pun` to start the TUI, or `pun -p "your prompt"` for one-shot.
        \\
    , .{});
}

pub fn printConfig(alloc: std.mem.Allocator, cfg: *Config) !void {
    _ = alloc;
    var buf: [4096]u8 = undefined;
    var fbs = std.io.fixedBufferStream(&buf);
    const w = fbs.writer();

    try w.print("=== pun config ===\n", .{});
    try w.print("active_profile: {s}\n", .{cfg.active_profile});
    if (cfg.active_provider) |p| try w.print("active_provider: {s}\n", .{p});
    if (cfg.active_model) |m| try w.print("active_model: {s}\n", .{m});
    try w.print("shell_disabled: {}\n", .{cfg.shell_disabled});
    try w.print("auto_yes: {}\n", .{cfg.auto_yes});

    try w.print("\n[providers]\n", .{});
    var pit = cfg.providers.iterator();
    while (pit.next()) |e| {
        const p = e.value_ptr.*;
        try w.print("  {s}:\n", .{p.name});
        try w.print("    kind: {s}\n", .{p.kind.toString()});
        try w.print("    default_model: {s}\n", .{p.default_model});
        if (p.api_key_env) |s| try w.print("    api_key_env: {s}\n", .{s});
        if (p.base_url) |s| try w.print("    base_url: {s}\n", .{s});
    }

    try w.print("\n[profiles]\n", .{});
    var prit = cfg.profiles.iterator();
    while (prit.next()) |e| {
        const p = e.value_ptr.*;
        try w.print("  {s}: provider={s} model={?s} temp={d:.2} max_tokens={d}\n", .{
            p.name, p.provider, p.model, p.temperature, p.max_tokens,
        });
    }

    try w.print("\n[shell]\n", .{});
    try w.print("  workspace: {s}\n", .{cfg.shell.workspace});
    try w.print("  allowlist: {d} entries\n", .{cfg.shell.allowlist.len});
    try w.print("  timeout_seconds: {d}\n", .{cfg.shell.timeout_seconds});
    try w.print("  allow_network: {}\n", .{cfg.shell.allow_network});

    try w.print("\n[security]\n", .{});
    try w.print("  workspace: {s}\n", .{cfg.security.workspace});
    try w.print("  audit_log: {s}\n", .{cfg.security.audit_log});
    try w.print("  vault_path: {s}\n", .{cfg.security.vault_path});
    try w.print("  prompt_injection_guard: {}\n", .{cfg.security.prompt_injection_guard});
    try w.print("  token_budget: per_session={d} per_step={d}\n", .{
        cfg.security.token_budget.per_session, cfg.security.token_budget.per_step,
    });

    const stdout = std.io.getStdOut().writer();
    try stdout.writeAll(fbs.getWritten());
}

fn stdoutPrint(comptime fmt: []const u8, args: anytype) !void {
    var buf: [4096]u8 = undefined;
    const out = try std.fmt.bufPrint(&buf, fmt, args);
    const stdout = std.io.getStdOut().writer();
    try stdout.writeAll(out);
}

test "loadConfig: missing file uses defaults" {
    var cfg = try loadConfig(std.testing.allocator, "/nonexistent.toml", null, null);
    defer cfg.deinit();
    try std.testing.expect(cfg.providers.contains("anthropic"));
}
